version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MasWag
  assignees:
  - MasWag
  labels:
  - dependencies

# Enable version updates for npm
- package-ecosystem: "npm"
  # Look for `package.json` and `lock` files in the `root` directory
  directory: "/"
  # Check the npm registry for updates every day (weekdays)
  schedule:
    interval: "daily"
