name: BuildManual
on: push

jobs:
  publish:
    name: Build manual
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and install the manual
        run: |
          export HOME=/root
          eval $(opam env)
          opam update
          opam pin add satysfi-class-cv-doc.opam "file://$PWD"
          satyrographos install
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: manual
          path: /root/.satysfi/dist/docs/class-cv-doc/manual.pdf
