name: regression_test
on: [push, pull_request]

jobs:
  regression-test:
    name: Run regression test
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: hidakatsuya/action-setup-diff-pdf@v1.3.0
      with:
        diff-pdf-version: '0.5'
    - name: Install Yarn dependencies
      run: yarn install
    - name: Install Satyrographos dependencies
      run: |
        export HOME=/root
        eval $(opam env)
        opam update
        opam pin add satysfi-class-cv.opam "file://$PWD"
        satyrographos install
    - name: Run regression tests
      run: |
        export HOME=/root
        eval $(opam env)
        yarn test --ci
