name: regression_test
on: [push, pull_request]

jobs:
  regression-test:
    name: Run regression test
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 20
    - name: Install dependencies
      run: apt-get update && apt-get install make automake g++ libpoppler-glib-dev poppler-utils libwxgtk3.0-gtk3-dev -y
    - name: Build and install diff-pdf
      run: |
        git clone https://github.com/vslavik/diff-pdf.git -b v0.5 --depth 1 /tmp/diff-pdf-src
        cd /tmp/diff-pdf-src
        ./bootstrap
        ./configure
        make
        make install
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install Yarn dependencies
      run: yarn install
    - name: Install Satyrographos dependencies
      run: |
        export HOME=/root
        eval $(opam env)
        opam update
        opam pin add satysfi-class-cv.opam "file://$PWD"
        satyrographos install
    - name: Run regression tests
      run: |
        export HOME=/root
        eval $(opam env)
        yarn test --ci
